.TH XYOKADI 1 "July 10, 2009"
.SH NAME
xyokadi \- commandline todo system
.SH SYNOPSIS
.B xyokadi
.br
.SH DESCRIPTION
.B xyokadi
is a wrapper for yokadi to run it in terminal.
.PP
.SH OPTIONS
xyokadi has no options
.SH SEE ALSO
.BR yokadi (1),
.BR yokadid (1).
.br
.SH SEE ALSO
Website: http://yokadi.github.com

Mailing List: http://sequanux.org/cgi-bin/mailman/listinfo/ml-yokadi
.SH AUTHOR
yokadi was written by Aurélien Gâteau <aurelien.gateau@free.fr> and Sébastien Renard <sebastien.renard@digitalfox.org>.
.PP
This manual page was written by Kartik Mistry <kartik@debian.org>,
for the Debian project (and may be used by others).
