#!/usr/bin/env python
# -*- coding: UTF-8 -*-
"""
Update from version 2 to version 3 of Yokadi DB

@author: Sébastien Renard <Sebastien.Renard@digitalfox.org>
@license: GPLv3
"""
import sys
from os.path import dirname, join

from sqlobject import connectionForURI, RelatedJoin, sqlhub, SQLObject

sys.path.append(join(dirname(__file__),"..", "src"))
import yokadi.db

def alterProjectTable():
    yokadi.db.Project.sqlmeta.addJoin(RelatedJoin("Keyword",
                                          createRelatedTable=False,
                                          intermediateTable="project_keyword",
                                          joinColumn="project_id",
                                          otherColumn="keyword_id"))

def main():
    sqlhub.processConnection = connectionForURI('sqlite:' + sys.argv[1])
    alterProjectTable()
    v=yokadi.db.Config.selectBy(name="DB_VERSION")[0]
    v.value="3"


if __name__ == "__main__":
    main()
# vi: ts=4 sw=4 et
