#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
"""
Update from version 8 to version 9 of Yokadi DB
Add a uuid field to the Task table, then populate it.

@author: Aurélien Gâteau <mail@agateau.com>
@license: GPL v3 or later
"""
import sys

from uuid import uuid1

from sqlalchemy import create_engine


def addTaskUuidColumn(conn):
    conn.execute("alter table task add column uuid")
    for row in conn.execute("select id from task"):
        taskId = row["id"]
        uuid = str(uuid1())
        conn.execute("update task set uuid = ? where id = ?", uuid, taskId)


def main():
    uri = "sqlite:///" + sys.argv[1]
    engine = create_engine(uri)
    with engine.begin() as conn:
        addTaskUuidColumn(conn)


if __name__ == "__main__":
    main()
# vi: ts=4 sw=4 et
