#!/usr/bin/env python2
# -*- coding: UTF-8 -*-
"""
Update from version 2 to version 3 of Yokadi DB

@author: Sébastien Renard <Sebastien.Renard@digitalfox.org>
@license: GPL v3 or newer
"""
import sys

try:
    from sqlobject import connectionForURI, sqlhub, SQLObject, ForeignKey
except ImportError:
    print("To run this update you need sqlobject")
    sys.exit(1)


# Fake tables (we only need table names)
class Keyword(SQLObject):
    pass


class Project(SQLObject):
    pass


class ProjectKeyword(SQLObject):
    project_id=ForeignKey('Project')
    keyword_id=ForeignKey('Keyword')


def createProjectKeywordTable():
    ProjectKeyword.createTable()


def main():
    sqlhub.processConnection = connectionForURI('sqlite:' + sys.argv[1])
    createProjectKeywordTable()


if __name__ == "__main__":
    main()
# vi: ts=4 sw=4 et
