#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
"""
Update from version 9 to version 10 of Yokadi DB
Add uuid fields to the Project and Task tables, then populate them.

@author: Aurélien Gâteau <mail@agateau.com>
@license: GPL v3 or later
"""
import sys

from uuid import uuid1

from sqlalchemy import create_engine


def addUuidColumn(conn, tableName):
    conn.execute("alter table {} add column uuid".format(tableName))
    for row in conn.execute("select id from {}".format(tableName)):
        id = row["id"]
        uuid = str(uuid1())
        conn.execute("update {} set uuid = ? where id = ?".format(tableName), uuid, id)


def main():
    uri = "sqlite:///" + sys.argv[1]
    engine = create_engine(uri)
    with engine.begin() as conn:
        addUuidColumn(conn, "project")
        addUuidColumn(conn, "task")


if __name__ == "__main__":
    main()
# vi: ts=4 sw=4 et
