#!/usr/bin/env python2
# -*- coding: UTF-8 -*-
"""
Update from version 4 to version 5 of Yokadi DB

@author: Sébastien Renard <Sebastien.Renard@digitalfox.org>
@license: GPL v3 or newer
"""
import sys

try:
    from sqlobject import connectionForURI, sqlhub
except ImportError:
    print("To run this update you need sqlobject")
    sys.exit(1)


def updateBugsKeywordsNames():
    for keyword in ("bug", "severity", "likelihood"):
        sqlhub.processConnection.query("update keyword set name='_%s' where name='%s'" % (keyword, keyword))

def removeTextWidthParam():
    sqlhub.processConnection.query("delete from config where name='TEXT_WIDTH'")

def main():
    sqlhub.processConnection = connectionForURI('sqlite:' + sys.argv[1])
    updateBugsKeywordsNames()
    removeTextWidthParam()

if __name__ == "__main__":
    main()
# vi: ts=4 sw=4 et
