#!/usr/bin/env python
# -*- coding: UTF-8 -*-
"""
Update from version 3 to version 4 of Yokadi DB

@author: Sébastien Renard <Sebastien.Renard@digitalfox.org>
@license: GPLv3
"""
import sys
from os.path import dirname, join

from sqlobject import connectionForURI, sqlhub, SQLObject, ForeignKey

sys.path.append(join(dirname(__file__),"..", "src", "yokadi"))
import db


def createRecurrenceTable():
    db.Recurrence.createTable()

def alterTaskTable():
    db.Task.sqlmeta.addColumn(ForeignKey("Recurrence", default=None))

def main():
    sqlhub.processConnection = connectionForURI('sqlite:' + sys.argv[1])
    createRecurrenceTable
    alterTaskTable()
    v=db.Config.selectBy(name="DB_VERSION")[0]
    v.value="4"


if __name__ == "__main__":
    main()
# vi: ts=4 sw=4 et
